# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -B package --file pom.xml -DskipTests
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    #- name: Download a Build Artifact
    #  uses: actions/download-artifact@v2.0.9
    - name: Release
      uses: damico/github-actions-maven-release@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        java-home: "${{ steps.setup-java-11.outputs.jdk-path }}"
        release-branch-name: "master"

        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@example.com"

        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        maven-publish-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"


